# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (4b89f88e-13f2-4990-bf5f-3ab2e4d5301f)'
    appType: 'functionAppLinux'
    appName: 'hitboxfunctions'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'