module.exports = Object.freeze({
    ACCELERATION: 2,
    VERTICALACCELERATION: 0.4,
    TERMINAL: 20,
    JUMPSPEED: 20,
    PLATFORMHEIGHT: 400,
    PLAYERWIDTH: 50,
    PLAYERHEIGHT: 80,
    SHUNTSPEED: 5,
    WIDTH: 960,
    HEIGHT: 540,
    WALLDAMPING: 0.75,
    DAMAGETHRESHOLD: 5,
    FRICTION: 0.99,
    BOOSTSPEED: 35,
    DUCKEDHEIGHT: 1/5,
    MAXPLAYERS: 10,
    BOOSTCOST: 60,
    MAXDISTANCE: 0,
    DEATHMETHODS: [" murdered ", " boxed ", " destroyed ", " hit ", " killed "],
    SUICIDEMETHODS: [" drowned", " killed themself", " died"]
});