name: backend

on:
  push:
    paths:
    - backend/**
    - .github/workflows/backend.yml

env:
  AZURE_WEBAPP_NAME: hitbox
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      working-directory: ./backend
      run: |
        npm install
        npm run build

    - name: Zip artifact for deployment
      working-directory: ./backend/build
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: hitbox
        path: ./backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: hitbox

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_ASOS }}
        package: .
