name: web

on:
  push:
    paths:
    - backend/**
    - .github/workflows/backend.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: npm run build
      run: npx @colyseus/cloud deploy --remote https://github.com/yusufzerdazi/hitbox.git
      working-directory: ./web
      env:
        CI: ""

  