name: backend

on:
  push:
    paths:
    - backend/**
    - .github/workflows/backend.yml

env:
  AZURE_WEBAPP_NAME: hitbox
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      working-directory: ./backend
      run: |
        npm install
        npm run build

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ASOS }}

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./backend
        clean: true
        restart: true

    - name: 'Deploy App Settings'
      id: app-settings
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        general-settings-json: '{"PLAYFAB_KEY": "${{ secrets.PLAYFAB_KEY }}", "IFTTT_KEY": "${{ secrets.IFTTT_KEY }}"}'
