name: backend

on:
  push:
    paths:
    - backend/**
    - .github/workflows/backend.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["backend/.colyseus-cloud.json"]'
      env:
        COLYSEUS_TOKEN: ${{ secrets.COLYSEUS_TOKEN }}
        
    - name: Deploy to Colyseus
      run: echo "Y" | npx @colyseus/cloud deploy
      working-directory: ./backend
      env:
        CI: ""

  