name: backend

on:
  push:
    paths:
    - backend/**
    - .github/workflows/backend.yml

env:
  AZURE_WEBAPP_NAME: hitbox
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      working-directory: ./backend
      run: |
        npm install
        npm run build

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./backend/build
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_ASOS }}
        target-path: /home/site/wwwroot
        type: Static