on:
  push:
    paths:
    - '**.bicep'
    - .github/workflows/bicep.yml
  workflow_dispatch:

name: infra_backend

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ASOS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ASOS }}
        resourceGroupName: hitbox
        template: ./bicep/backend.bicep
        failOnStdErr: false     
        scope: resourcegroup
